### PR TITLE
General cleanup

### PR DESCRIPTION
**Pull request by corysimmons**
After this I'll work on the npm package for this. :water_buffalo:

### CODE REVIEW

**Comment by antonagestam** [comment]
Wow, thanks for the contribution! What's the package.json for? :)

**Comment by corysimmons** [comment]
@antonagestam So we could go ahead and grab the squash-css npm package name.

**Comment by corysimmons** [comment]
If we end up not using it, we can unpublish

**Comment by antonagestam** [comment]
@corysimmons What would be the benefits of publishing the tool on npm? Wouldn't PyPI be more proper for a Python package? :)

**Comment by corysimmons** [comment]
It's a frontend tool though. The majority of frontend tools are npm-centric (grunt, gulp, stylus, etc.), so it makes sense to package this as an npm package.

### Installation
- `npm install -g squash-css`

### Usage
- `squash-css foo.css bar.css` or `squash-css -w foo.css bar.css`

### As a Stylus Lib?
- `stylus -u squash-css -w foo.styl`

**Comment by corysimmons** [comment]
You can certainly keep the main script in Python and package it for use in PyPi if you want, but I'm sure people would be more likely to use it if it were packaged for npm as well.

`/$.02`

**Comment by corysimmons** [comment]
Anything holding this up from getting merged?

**Comment by antonagestam** [comment]
@corysimmons Let's remove the package.json file for now, at least until the library is actually usable through NPM (at the moment there's no CLI) and I'll merge the rest.

**Comment by corysimmons** [comment]
@antonagestam :+1: I unpublished the package too

**Pull request merged**
